version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pd1234
      POSTGRES_DB: financing
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:pd1234@postgres:5432/financing?schema=public
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
